const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;

const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

const GOOGLE_MAPS_API_KEY = import.meta.env.VITE_GOOGLE_MAPS_API_KEY;

window.SUPABASE_URL = SUPABASE_URL;

window.SUPABASE_ANON_KEY = SUPABASE_ANON_KEY;

window.GOOGLE_MAPS_API_KEY = GOOGLE_MAPS_API_KEY;